import StyleDictionary from 'style-dictionary';

// Custom TypeScript format for v5
StyleDictionary.registerFormat({
  name: 'typescript/es6-declarations',
  format: ({ dictionary }) => {
    return `// This file is auto-generated by Style Dictionary
// Do not edit directly

${dictionary.allTokens.map(token => {
  const name = token.name;
  const value = JSON.stringify(token.value);
  return `export const ${name}: string = ${value};`;
}).join('\n')}
`;
  }
});

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/css/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            outputReferences: true
          }
        }
      ]
    },
    scss: {
      transformGroup: 'scss',
      buildPath: 'dist/scss/',
      files: [
        {
          destination: '_tokens.scss',
          format: 'scss/variables',
          options: {
            outputReferences: true
          }
        }
      ]
    },
    js: {
      transformGroup: 'js',
      buildPath: 'dist/js/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6'
        }
      ]
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'src/',
      files: [
        {
          destination: 'tokens.generated.ts',
          format: 'typescript/es6-declarations'
        }
      ]
    }
  }
};