name: 'Build Workspace Packages'
description: 'Builds all workspace packages in the correct dependency order'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci --ignore-scripts
      shell: bash

    - name: Build workspace packages in dependency order
      run: |
        npm run build -w packages/vite-config
        npm run build -w packages/applet-core
        npm run build -w packages/applet-meta  
        npm run build -w packages/applet-cli
        npm run build -w packages/applet-host
        npm run build -w packages/openapi-msw
        npm run build -w packages/mui-applet-core
        npm run build -w packages/mui-components
        npm run build -w packages/mui-applet-devtools
        npm run build -w packages/dataview
        npm run build -w packages/ui-core
      shell: bash

    - name: Build remaining packages
      run: npm run build:libs
      shell: bash