name: "Build Workspace Packages"
description: "Builds all workspace packages in the correct dependency order"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "npm"

    - name: Install Dependencies
      run: rm -f package-lock.json && npm install --ignore-scripts --legacy-peer-deps
      shell: bash

    - name: Build all packages with Turbo (excluding Storybook)
      run: npm run build --workspace=@smbc/ui-core && turbo run build --filter="!@smbc/mui-storybook"
      shell: bash
