name: 'Local Changesets Action'
description: 'Local implementation of changesets action for version management and publishing'
inputs:
  publish:
    description: 'The command to use to publish packages'
    required: false
    default: 'npm run changeset:publish'
  version:
    description: 'The command to use to version packages'
    required: false
    default: 'npm run changeset:version'
  commit:
    description: 'Commit message for version updates'
    required: false
    default: 'Version Packages'
  title:
    description: 'Pull request title'
    required: false
    default: 'Version Packages'
outputs:
  published:
    description: 'Whether packages were published'
  publishedPackages:
    description: 'JSON array of published packages'
  hasChangesets:
    description: 'Whether there are changesets to process'
  pullRequestNumber:
    description: 'The PR number for version updates'
runs:
  using: 'composite'
  steps:
    - name: Run changesets script
      shell: bash
      run: |
        # Export inputs as environment variables
        export PUBLISH_COMMAND="${{ inputs.publish }}"
        export VERSION_COMMAND="${{ inputs.version }}"
        export COMMIT_MESSAGE="${{ inputs.commit }}"
        export PR_TITLE="${{ inputs.title }}"
        
        # Run the changesets script
        ${{ github.action_path }}/../../../scripts/changesets-action.sh