name: Changesets (Local Action)
on:
  push:
    branches:
      - main

jobs:
  changesets:
    name: Manage versions and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build packages
        run: npm run build
      
      # Use local composite action if you prefer over shell script
      - name: Changesets
        uses: ./.github/actions/changesets
        with:
          publish: npm run changeset:publish
          version: npm run changeset:version
          commit: "Version Packages"
          title: "Version Packages"