name: Deploy Apps to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install Dependencies with legacy peer deps
        run: |
          rm -f package-lock.json
          npm install --ignore-scripts --legacy-peer-deps

      - name: Build workspace packages (excluding apps)
        run: |
          npx turbo run build \
            --filter="!@smbc/gh-pages" \
            --filter="!@smbc/mui-host-dev" \
            --filter="!@smbc/mui-ewi" \
            --filter="!@smbc/mui-storybook" \
            --continue

      - name: Create deployment directory
        run: mkdir -p ./deploy

      - name: Build GitHub Pages Index
        run: |
          cd apps/gh-pages
          npm run build
        env:
          NODE_ENV: development
          VITE_BASE_PATH: "/${{ github.event.repository.name }}/"

      - name: Copy Index to deployment root
        run: |
          cp -r ./apps/gh-pages/dist/* ./deploy/
          mkdir -p ./deploy/assets
          cp ./apps/mui-storybook/public/assets/logo*.png ./deploy/assets/

      - name: Build MUI Host Dev
        run: |
          cd apps/mui-host-dev
          npm run build
        env:
          NODE_ENV: development
          VITE_BASE_PATH: "/${{ github.event.repository.name }}/mui-host-dev/"

      - name: Copy MUI Host Dev build
        run: |
          mkdir -p ./deploy/mui-host-dev
          cp -r ./apps/mui-host-dev/dist/* ./deploy/mui-host-dev/
          mkdir -p ./deploy/mui-host-dev/assets
          cp ./apps/mui-storybook/public/assets/logo*.png ./deploy/mui-host-dev/assets/

      - name: Build EWI App
        run: |
          cd apps/mui-ewi
          npm run build -- --mode development
        env:
          NODE_ENV: development
          VITE_BASE_PATH: "/${{ github.event.repository.name }}/ewi/"
          VITE_USE_MOCKS: "true"

      - name: Copy EWI build
        run: |
          mkdir -p ./deploy/ewi
          cp -r ./apps/mui-ewi/dist/* ./deploy/ewi/
          mkdir -p ./deploy/ewi/assets
          cp ./apps/mui-storybook/public/assets/logo*.png ./deploy/ewi/assets/

      - name: Build Storybook
        run: |
          cd apps/mui-storybook
          npm run build-storybook -- --output-dir dist
        env:
          NODE_ENV: development
          VITE_BASE_PATH: "/${{ github.event.repository.name }}/storybook/"

      - name: Copy Storybook build
        run: |
          mkdir -p ./deploy/storybook
          cp -r ./apps/mui-storybook/dist/* ./deploy/storybook/
          mkdir -p ./deploy/storybook/assets
          cp ./apps/mui-storybook/public/assets/logo*.png ./deploy/storybook/assets/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./deploy"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
