name: Deploy MUI Host Dev to GitHub Pages (Improved)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install Dependencies with legacy peer deps
        run: |
          rm -f package-lock.json
          npm install --ignore-scripts --legacy-peer-deps

      - name: Build UI Core package first
        run: npm run build --workspace=@smbc/ui-core

      - name: Build workspace packages (excluding problematic ones)
        run: |
          npx turbo run build \
            --filter="!@smbc/mui-storybook" \
            --filter="!@smbc/mui-storybook-old" \
            --continue

      - name: Build MUI Host Dev
        run: |
          cd apps/mui-host-dev
          npm run build
        env:
          # Enable production optimizations
          NODE_ENV: production
          # Set base path for GitHub Pages (auto-detects repository name)
          VITE_BASE_PATH: "/${{ github.event.repository.name }}/"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './apps/mui-host-dev/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4